# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p1', '0002_auto_20170312_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='am_registrations',
            fields=[
                ('registrations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='p1.registrations')),
            ],
            bases=('p1.registrations',),
        ),
    ]
