# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 05:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('jid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('job_status', models.BooleanField(default=False)),
                ('job_desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('machine_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('os', models.CharField(max_length=32)),
                ('arch', models.CharField(choices=[('amd64', '64 bit arch'), ('i386', '32 bit arch')], max_length=8)),
                ('ip', models.CharField(max_length=16)),
                ('is_live', models.BooleanField(default=False)),
                ('in_use', models.BooleanField(default=False)),
                ('status_last_update', models.DateTimeField(default=datetime.datetime(2017, 2, 11, 5, 14, 33, 111346))),
            ],
        ),
        migrations.CreateModel(
            name='machine_to_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=128)),
                ('jid', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=32)),
            ],
        ),
    ]
