# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status_last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 7, 8, 0, 14, 116617)),
        ),
    ]
