# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-17 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0002_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='log',
        ),
    ]
