# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0003_auto_20170124_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status_last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 24, 17, 59, 20, 293157)),
        ),
    ]
