# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-24 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0004_auto_20161218_0716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
        migrations.DeleteModel(
            name='posts',
        ),
    ]
