# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0009_auto_20170314_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status_last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 10, 54, 46, 12873)),
        ),
    ]
