# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0012_auto_20170422_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_desc',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status_last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 20, 12, 34, 51, 924745)),
        ),
    ]
