# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p1', '__first__'),
    ]

