# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn_name', models.CharField(max_length=128)),
                ('hook_name', models.CharField(max_length=64)),
            ],
        ),
    ]
